version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /home/jack/hiding_app/nginx.conf:/etc/nginx/nginx.conf
      - /home/jack/hiding_app/nginx/error.log:/etc/nginx/error.log
      - /home/jack/hiding_app/nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - VIRTUALHOST=jack.jacktimmins.com
    volumes:
      - "./:/app"

